development: &non_production_settings
  site_url: http://homedevel.no-ip.org:3000
  site_name: "Bigupload"
  admin_email: andrei@nextbyte.ro
  
test:
  <<: *non_production_settings

staging:
  site_url: http://bigupload.bizland.ro
  site_name: "Bigupload"
  admin_email: andrei@nextbyte.ro  
  
production:
  site_url: http://www.bigupload.com
  site_name: Bigupload
  admin_email: dudes@bigupload.com
